#!/bin/bash

source /home/zangar/Documents/order_service/scripts/env.sh

psql -U $ROOT_USER_PSQL -p $DB_PORT -h $DB_HOST \
    -c "CREATE ROLE $USER_ORDER_SERVICE WITH PASSWORD '$PASSWORD_ORDER_SERVICE';"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $DB_HOST \
    -c "CREATE DATABASE $DB_ORDER_SERVICE;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $DB_HOST \
    -c "ALTER ROLE $USER_ORDER_SERVICE WITH LOGIN;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $DB_HOST \
    -c "GRANT ALL PRIVILEGES ON DATABASE $DB_ORDER_SERVICE TO $USER_ORDER_SERVICE;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $DB_HOST \
    -c "GRANT pg_write_server_files TO $USER_ORDER_SERVICE;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $DB_HOST \
    -c "GRANT pg_read_server_files TO $USER_ORDER_SERVICE;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $DB_HOST \
    -c "GRANT CREATE ON SCHEMA public TO $DB_ORDER_SERVICE;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $DB_HOST \
    -c "ALTER USER $USER_ORDER_SERVICE WITH SUPERUSER;"
PGPASSWORD=$PASSWORD_ORDER_SERVICE psql -U $USER_ORDER_SERVICE -p $DB_PORT -h $DB_HOST \
    -c "CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    total_price DECIMAL(10,2) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);"

PGPASSWORD=$PASSWORD_ORDER_SERVICE psql -U $USER_ORDER_SERVICE -p $DB_PORT -h $DB_HOST \
    -c 'CREATE TABLE order_items (
    id SERIAL PRIMARY KEY,
    order_id INT REFERENCES orders(id) ON DELETE CASCADE,
    product_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL
);'
